### PR TITLE
Add 'secrets upload' command for importing files

### PR DESCRIPTION
**Pull request by Piccirello**
`doppler secrets upload <filepath>` will import the contents of the specified file to a config. It currently supports json and env.

I'm toying with calling this `doppler secrets import` instead. What do you guys think?

### CODE REVIEW

**Review by rgmvisser — APPROVED** [review]

**Review by ryan-blunden — APPROVED** [review]
Awesome!

**Comment by ryan-blunden** [comment]
@Piccirello are there any limitations format wise, such as no nested JSON or env files requiring values to be quoted?

**Comment by Piccirello** [comment]
Nothing like that, as far as I'm aware. We do support nested JSON. This uses the same code as our "Upload env" feature on our dashboard.

**Pull request merged**
