### PR TITLE
Add install support for Git Bash for Windows

### PR DESCRIPTION
**Pull request by watsonian**
This adds support for Git Bash for Windows to the install script.

Solves #302.

### CODE REVIEW

**Review by Piccirello — COMMENTED** [review]
This is a really nice addition. Could you add a test for this functionality to our "Test install.sh" script (`.github/workflows/install.yml`)? This will ensure that we don't accidentally break this functionality in the future - and that it's working as expected right now.

**Comment by nmanoogian** [comment]
This is awesome! Can you re-request my review once you're happy with that action workflow?

**Comment by watsonian** [comment]
@nmanoogian Yep, will do! Just trying to figure out how to get this to run in a Git Bash shell...

**Comment by watsonian** [comment]
Okay, I've got a workflow test working. Not sure if we want anything beyond what it's doing there. Ready for re-review though!

**Review by nmanoogian — APPROVED** [review]
This looks great to me! I'll defer to @Piccirello for final approval

**Review by Piccirello — APPROVED** [review]
Excellent work 👍

**Pull request merged**
